### ISSUE TITLE
Fehler  bei  installation

### ISSUE THREAD

**Issue by schpuntik** [Schnippsche/solarreader#1]
In moment   ich steh auf dem schlauch. Webinstaller  und solarreader  sind unterschiedliche Projekte?  Beim Webinstaller  fehlt Datei  und  hier finde nicht  script startup.sh. Was mache ich falsch? 

`orangepi@orangepizero2:~$ sudo wget -q -O - https://solaranzeige.schnippsche.de/webupgrade | sh
/var/www/html/webinstaller.tar: No such file or directory
webinstaller konnte nicht heruntergeladen werden
`

**Comment by Schnippsche** [comment]
Webinstaller und solarreader sind unterschiedliche Projekte. Webinstaller für Solaranzeige wird nicht mehr supported und steht auch nicht mehr zur Verfügung. Solarreader ist ein vollkommen unabhängiges und neues Projekt auf Java Basis.
Die Start und Stop Skripte findet man im Ordner "src/scripts"

**Comment by schpuntik** [comment]
Guten Morgen, durch  das schließen des  Issues das  problem ist immer noch da!
1.  Das ist  andere  Projekt  ist  jetzt klar.
2. Ich  habe Debian  auf OrangePI  Zero 2 
3. Abhängigkeiten ist  nicht ganz klar, default-jdk  habe installiert.
4. In README  steht  startup.sh  für Linux starten. Gibst aber nicht.Es gibt  in "src/scripts/start_solarreader.sh" soweit klar.
5. Durch   start  in der konsole "sh  src/scripts/start_solarreader.sh"  bleibt alles hängen im warte zustand. Datei nohup.out solarreader.pid werden angelegt.
6. Gehe in Browser  und ruf ipadressePi:8080  passiert nichts.
Ich  vermute das fehlen noch  Abhängigkeiten, Apache  oder andere  web-server. Oder muss  java kompilieren aber wie steht nicht im README.


Edit:   Fertige Datei downloaded und gestartet.
`wget https://github.com/Schnippsche/solarreader/releases/download/V1.1/solarreader-1.1.jar`
 `java -jar solarreader-1.1.jar`
Web  funktioniert soweit.

**Comment by Schnippsche** [comment]
Hallo, man muss nicht Java kompilieren, wenn man das fertige Release nimmt (solarreader.jar)
1. Das aktuelle Release runterladen, zu finden [hier](https://github.com/Schnippsche/solarreader/releases/download/V1.1/solarreader-1.1.jar)
2. Die jar umbenennen in solarreader.jar, damit das Skript nicht angepasst werden muss
3.  Das Start-Skript herunterladen, zu finden [hier](https://github.com/Schnippsche/solarreader/blob/main/src/scripts/start_solarreader.sh)
4. Das Stop-Skript herunterladen, zu finden [hier](https://github.com/Schnippsche/solarreader/blob/main/src/scripts/stop_solarreader.sh)
5. Alles in ein Verzeichnis packen
6. Die Skripte mit Ausführungsrechten ausstatten z.B. mit chmod 755 *solarreader.sh
7. Das Skript start_solarreader.sh auf Konsole ausführen und zweimal Enter drücken. Damit ist die Konsole nicht mehr blockiert.

Einen Apache benötigt man nicht!
Sollte der Port bereits belegt sein, kann man den im Start-Skript abändern (-Dport=8080)
Auf meinem Raspberry mit Minimal Raspbian läuft das tadellos ohne extra installierten Apache...
