### ISSUE TITLE
Fronius Symo über Modbus TCP?

### ISSUE THREAD

**Issue by mdkeil** [Schnippsche/solarreader#2]
Ich gehe davon aus, dass die Fronius Symo - Serie noch nicht implementiert ist? Ich hätte ggfs. den Bedarf meinen WR entsprechend auszulesen in einem Intervall zwischen 10-30s. Aktuell lese ich ihn minütlich über die Fronius-API via Solaranzeige aus mit einen umfangreichen Folgescript (_math.php). Würde diese Funktionalität erhalten bleiben?

**Comment by mdkeil** [comment]
Ich habe mir gerade mal die fronius.json angeschaut. Was ich beim Überfliegen nicht gefunden habe, sind die Werte eines optional angebundenen (über Modbus RTU) Fronius Smartmeters.. Mit Solaranzeige sind die Werte ja im Measurement "Meter" abgelegt. Diese Werte sind für mich essentiell, da ich zwingend den Netzbezug / Einspeisung / Gesamtverbrauch benötige.

**Comment by mdkeil** [comment]
Ich lese nun beide Fronius WR + das Fronius Smartmeter in HomeAssistant über die Sunspec Integration aus und schreibe sie in die influxdb. Ich muss nun leider etwas Arbeit und Zeit investieren, um die vorhanden Daten aus der Solaranzeige in eine neue Datenbankstruktur zu schreiben.. ggfs. bekomme ich die Daten über HA in die selbe Struktur abgelegt.. muss ich mal schauen.

**Comment by mdkeil** [comment]
Ich werde mich heute Abend mal ranmachen, für den Symo, Primo und dem Smartmeter die entsprechenden Konfigurationsfiles anzulegen. Muss WR und Smartmeter separat behandelt werden?.. Smartmeter wird ja über den WR ausgelesen.. Symo ist Slave=1, der Primo ist 2, und das Fronius Smarzmeter Slave=240.

Über HA habe ich bereits alle Daten in entsprechenden Entitäten hingelegt, nur mir gefällt nicht, wie die Daten in der Influxdb gespeichert werden, zudem haben alle Werte unterschiedliche Timestamps.

**Comment by mdkeil** [comment]
Ich habe für den Fronius Smartmeter das entsprechende [json-File](https://github.com/mdkeil/solarreader/blob/main/src/main/resources/specifications/fronius_meter_sunspec_model_M21X_float.json) erstellt. Daher bitte eine modbus-tcp Verbindung dafür implementieren. Folgende Punkten sollten abgefragt werden:
- IP + Port
- slave / addresse (könnte aber auch auf 240 gesetzt werden, da dies der Standardwert ist)

Ich konnte es natürlich noch nicht auf Funktion testen. Darüber hinaus ist noch nicht Bezug und Einspeisung implementiert, da ich nicht genau weis, was als Calulation eingetragen werden muss, wenn ich z.B. für Bezug nur die positiven Werten aus dem Datenfeld "W" / AC Power value filtern möchte.. gleiches gilt für die negativen Werte für die Einspeisung.

**Comment by Schnippsche** [comment]
Hallo,

ist dein Fronius Modell so anders als die bereits entwickelte json für 
Fronius Symo Wechselrichter?
Wie heisst dein Modell genau und hast du evtl. die Spezifikation als pdf 
zur Hand, die du mir zur Verfügung stellen könntest?

Kannst mich auch gerne direkt anschreiben als über git issues.
Mail an ***@***.***


Zu den Berechnungen: Schau mal in die Mathematik Bibliothek 
https://github.com/Schnippsche/solarreader/blob/main/src/main/java/de/schnippsche/solarreader/backend/utils/MathEvalBigDecimal.java

Da könnte was passendes dabei sein. Eventuell hilft ein max(0, (W / AC))

Viele Grüße
Stefan


Am 2022-11-21 09:35, schrieb mdkeil:

**Comment by mdkeil** [comment]
Aktuell kann ich mal garkeinen Fronius auswählen, obgleich zumindest ein entsprechenden json-File vorhanden ist. Darüber hinaus muss zwingend unterschieden werden, ob es sich um eine RTU oder TCP Verbindung handelt, da die Registeradressen unterschiedlich sind. Im Grunde wird ja der Datamanager von einem Fronius Symo / Primo ausgelesen und mit der slave-ID gebe ich an, welches angebundene Gerät adressiert wird.

Hier mal die enstprechende Doku, welche ich sehr gut finde. (Startadressen sind abhängig davon, ob in den Einstellungen float oder int+SF gewählt ist) - ich würde float festlegen.

https://www.fronius.com/~/downloads/Solar%20Energy/Operating%20Instructions/42,0410,2049.pdf
https://www.fronius.com/~/downloads/Solar%20Energy/Operating%20Instructions/SE_EI_Modbus_Sunspec_Maps_State_Codes_Events_EN.zip


Aktuell liegen mir ja in HomeAssitant alle relevanten Register vor, nur ist der implementierte Export nach influxdb nicht  kompatibel mit Solaranzeige. Ich müsste mir also ein entsprechendes Script schreiben, was alle Daten solaranzeige-gerecht über die influxdb-API in die Datenbank schreibt, ist wahrscheinlich auch gut machbar, dafür habe ich aber auch keine Zeit. :)

Edit: Die Mailadresse wird mir nicht angezeigt :) Sonst schreib mir die als PM im solaranzeige-Forum, wenn darüber die Kommunikation schneller ist.

Edit2: Frage: Ist es möglich für eine databasefield-calculation auf "sourcevalues" anderer Geräte zurückzugreifen? -- Für die Berechnung z.B. vom Eigenverbrauch werden ja Daten vom Smartmeter und vom Wechselrichter benötigt.

**Comment by mdkeil** [comment]
> ist dein Fronius Modell so anders als die bereits entwickelte json für Fronius Symo Wechselrichter?

Kann ich so nicht sagen, da ich es leider nicht ausprobieren kann, da kein Fronius WR auswählbar ist.. wobei für mich eigentlich das Smartmeter wichtiger wäre-- ich habe mal die Fronius.java überflogen.. wenn ich es richtig gesehen habe, wird auch ein möglicher Fronius Smartmeter abgefragt..
