### ISSUE TITLE
Fronius Modbus Register - Model Angabe

### ISSUE THREAD

**Issue by mdkeil** [Schnippsche/solarreader#3]
Um nicht für jedes Fronius-Model eine seperate json-Datei zu erzeugen, wäre es praktikabler, wenn initial die "ID" ausgelesen wird und dann intern die korrekte Register-Map ausgewählt wird. Optional könnte man das Model auch abfragen und dann die Registermap(s) zurordnen.
Es würde dann nur noch eine json-Datei geben, wo dann anhand der Modelnummer unterschiedliche "Register-Gruppen" ausgelesen werden.. so ähnlich funktioniert das auch in der sunspec-integration von Homeassistent, wo ich dann auch manuell unterschiedliche Registergruppen (je nach Model) aus bzw. abwählen kann, in Abhängigkeit welche Informationen man benötigt.

**Comment by Schnippsche** [comment]
Hallo,
ja das klingt gut und ist auch technisch machbar bzw. in Teilen schon 
realisiert..
Problem ist immer nur an die Protokolle der verschiedenen Geräte zu 
kommen.

Ich habe die Daten ja eher aus dem Solaranzeige-Projekt-Code rausgelesen 
ohne Gewähr, dass das alles so stimmt.
Falls du da die Protokolle hast und mir geben kannst, wäre das natürlich 
toll.

Viele Grüße
Stefan
Am 2022-11-22 08:12, schrieb mdkeil:
