### ISSUE TITLE
2023-02-08 05:39:49.829 [main] InfluxExporter:97 ERROR: unsupported or unknown influx DB version v2.1.1

### ISSUE THREAD

**Issue by klausstorz** [Schnippsche/solarreader#4]
Beim Versuch, mit der InfluxDB zu verbinden, bekomme ich die Fehlermeldung

2023-02-08 05:39:49.829 [main] InfluxExporter:97 ERROR: unsupported or unknown influx DB version v2.1.1

Wird die Version 2.1.1 wirklich nicht unterstützt? Welche Versionen  werden denn unterstützt?

**Comment by Schnippsche** [comment]
Prinzipiell funktioniert die Software sowohl mit Influx V1 und V2. Anscheinend hat sich bei Influx was bei der Rückgabe der Version geändert und solarreader erkennt die Version nicht. Normalerweise wurde nur die Versionsnummer zurückgeliefert; in der Version ab 2.1 wird wohl noch ein 'v' davorgestellt. Das wird in der nächsten Version behoben sein. Sollte Interesse an einer Vorabversion zum Testen bestehen gerne per Mail an support@solarreader.de wenden.
